#!/bin/sh
if [ -d $APP_PATH/MangroveIPlug.app ]; then
  pluginkit -a $APP_PATH/MangroveIPlug.app/Contents/PlugIns/MangroveIPlug.appex
  echo "Force register auv3"
else
  echo "App path doesn't exist yet, cant force register auv3"
fi

